### ISSUE TITLE
does not apply to kernel 4.4?

### ISSUE THREAD

**Issue by aceman444** [graysky2/kernel_gcc_patch#14]
Looks like this suddenly does not apply to kernel 4.4 (worked fine up to 4.3):

checking file arch/x86/include/asm/module.h
Hunk %1 FAILED at 15.
Hunk %2 FAILED at 33.
2 out of 2 hunks FAILED
checking file arch/x86/Kconfig.cpu
Hunk %1 succeeded at 147 (offset 10 lines).
Hunk %2 succeeded at 156 (offset 10 lines).
Hunk %3 FAILED at 154.
Hunk %4 succeeded at 310 (offset 60 lines).
Hunk %5 FAILED at 268.
Hunk %6 succeeded at 393 (offset 109 lines).
Hunk %7 FAILED at 321.
Hunk %8 FAILED at 352.
Hunk %9 FAILED at 380.
5 out of 9 hunks FAILED
checking file arch/x86/Makefile
Hunk %1 FAILED at 94.
1 out of 1 hunk FAILED
checking file arch/x86/Makefile_32.cpu
Hunk %1 FAILED at 23.
Hunk %2 FAILED at 32.
2 out of 2 hunks FAILED

**Comment by Yukariin** [comment]
I use this patch successfully fith 4.4.1

**Comment by graysky2** [comment]
Confirmed here too; suggest you clean your tree and try again.  Closing.
```
% patch -Np1 -i enable_additional_cpu_optimizations_for_gcc_v4.9+_kernel_v3.15+.patch 
patching file arch/x86/include/asm/module.h
patching file arch/x86/Kconfig.cpu
Hunk #1 succeeded at 147 (offset 10 lines).
Hunk #2 succeeded at 156 (offset 10 lines).
Hunk #3 succeeded at 164 (offset 10 lines).
Hunk #4 succeeded at 317 (offset 10 lines).
Hunk #5 succeeded at 335 (offset 10 lines).
Hunk #6 succeeded at 408 (offset 10 lines).
Hunk #7 succeeded at 445 (offset 10 lines).
Hunk #8 succeeded at 476 (offset 10 lines).
Hunk #9 succeeded at 504 (offset 10 lines).
patching file arch/x86/Makefile
Hunk #1 succeeded at 104 (offset 10 lines).
patching file arch/x86/Makefile_32.cpu
```

**Comment by aceman444** [comment]
Yes, confirming. Downloading a full tree of 4.4.1 solves the problem. Sorry for bothering.

**Comment by graysky2** [comment]
> Yes, confirming. Downloading a full tree of 4.4.1 solves the problem. Sorry for bothering.

Not a bother, thank you for reporting and glad you're problem is solved.

**Comment by aceman444** [comment]
I still do not understand what happened, as I updated from 4.3 to 4.4 using the kernel differential patches and the 4.4 kernel could be build and ran fine. So it shouldn't have been busted. I do not understand why your patch didn't apply to it. It looks like you patch was partially applied to the new tree (I can see references to e.g. MNATIVE option) and I didn't notice that. Then, applying or reverting your patch on the tree again failed in that state.
